server:
  port: 8086
spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: config-service
  cloud:
    config:
      enabled: true
      uyri: http://localhost:8888
